name: CI
on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: DerYeger/yarn-setup-action@master
              with:
                  version: 7
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: 'yarn'

            - run: yarn install --frozen-lockfile
            - run: yarn test
