name: CI
on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: 'yarn'

            - name: Install Yarn
              uses: DerYeger/yarn-setup-action@master
              with:
                  node-version: 16.x

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Linter
              run: yarn lint

    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Install Yarn
              uses: DerYeger/yarn-setup-action@master
              with:
                  node-version: 16.x

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Tests
              run: yarn test
